---
planes:
  - 'B74'
  - 'A34'
  - 'B78'
  - 'B38'
  - 'A38'
  - 'B77'
  - 'A33'
  - 'MD11'

liveries:
  - 'ACA'
  - 'TSC'
  - 'SWG'
  - 'POE'
  - 'ROU'
  - 'JZA'
  - 'WEN'
  - 'SKV'
  - 'EDV'
  - 'ENY'
  - 'LOF'
  - 'CRQ'
  - 'AIE'
  - 'WJA'
  - 'HYD'
